package com.uklanafood.restaurant;

import android.Manifest;import android.content.Intent;import android.content.pm.PackageManager;import android.graphics.Color;import android.graphics.Typeface;import android.os.Build;import android.os.Bundle;import android.os.Handler;import android.os.Looper;import android.view.Gravity;import android.view.View;import android.widget.Button;import android.widget.CompoundButton;import android.widget.LinearLayout;import android.widget.ProgressBar;import android.widget.Switch;import android.widget.TextView;import android.widget.Toast;import androidx.activity.result.ActivityResultLauncher;import androidx.activity.result.contract.ActivityResultContracts;import androidx.appcompat.app.AlertDialog;import androidx.appcompat.app.AppCompatActivity;import androidx.core.content.ContextCompat;import org.json.JSONArray;import org.json.JSONObject;import java.util.HashSet;import java.util.Set;

public class MainActivity extends AppCompatActivity{
 private LinearLayout ordersContainer;private ProgressBar progress;private TextView statusText,totalText,pendingCount,doneCount;private Switch openSwitch;private String tab="pending";private final Handler handler=new Handler(Looper.getMainLooper());private final Set<String> knownPending=new HashSet<>();private boolean firstLoad=true,ignoreSwitch=false;
 private final ActivityResultLauncher<String> permissionLauncher=registerForActivityResult(new ActivityResultContracts.RequestPermission(),g->{});
 private final Runnable poll=new Runnable(){public void run(){loadAll(false);handler.postDelayed(this,AppConfig.REFRESH_MS);}};
 @Override protected void onCreate(Bundle b){super.onCreate(b);if(!SessionManager.loggedIn(this)){login();return;}setContentView(R.layout.activity_main);ordersContainer=findViewById(R.id.ordersContainer);progress=findViewById(R.id.progressBar);statusText=findViewById(R.id.statusText);totalText=findViewById(R.id.runningTotal);pendingCount=findViewById(R.id.pendingCount);doneCount=findViewById(R.id.doneCount);openSwitch=findViewById(R.id.openSwitch);((TextView)findViewById(R.id.restaurantName)).setText("🏪 "+SessionManager.name(this));((TextView)findViewById(R.id.restaurantPhone)).setText(SessionManager.phone(this));findViewById(R.id.ringtoneButton).setOnClickListener(v->startActivity(new Intent(this,RingtoneSettingsActivity.class)));findViewById(R.id.logoutButton).setOnClickListener(v->{SessionManager.clear(this);login();});findViewById(R.id.refreshButton).setOnClickListener(v->loadAll(false));findViewById(R.id.pendingTab).setOnClickListener(v->{tab="pending";styleTabs();loadOrders(false);});findViewById(R.id.doneTab).setOnClickListener(v->{tab="done";styleTabs();loadOrders(false);});findViewById(R.id.resetTotalButton).setOnClickListener(v->confirmReset());openSwitch.setOnCheckedChangeListener(this::toggleOpen);requestNotificationPermission();styleTabs();loadAll(true);}
 @Override protected void onResume(){super.onResume();handler.removeCallbacks(poll);handler.postDelayed(poll,AppConfig.REFRESH_MS);}
 @Override protected void onPause(){handler.removeCallbacks(poll);super.onPause();}
 private void requestNotificationPermission(){if(Build.VERSION.SDK_INT>=33&&ContextCompat.checkSelfPermission(this,Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)permissionLauncher.launch(Manifest.permission.POST_NOTIFICATIONS);}
 private void login(){startActivity(new Intent(this,LoginActivity.class));finish();}
 private void forceLogin(){SessionManager.clear(this);Toast.makeText(this,"Login expired. Dobara login karein.",Toast.LENGTH_LONG).show();login();}
 private void loadAll(boolean initial){loadDashboard();loadOrders(initial);}
 private void loadDashboard(){new Thread(()->{try{JSONObject r=ApiClient.get(this,AppConfig.DASHBOARD_URL);if(r.optInt("_http_code")==401){runOnUiThread(this::forceLogin);return;}if(!r.optBoolean("ok"))throw new Exception(r.optString("message","Dashboard load nahi hua"));runOnUiThread(()->{JSONObject a=r.optJSONObject("restaurant");ignoreSwitch=true;openSwitch.setChecked(a!=null&&a.optBoolean("is_open"));ignoreSwitch=false;updateOpenLabel(openSwitch.isChecked());pendingCount.setText(String.valueOf(r.optInt("pending_count")));doneCount.setText(String.valueOf(r.optInt("done_count")));((Button)findViewById(R.id.pendingTab)).setText("PENDING\n"+r.optInt("pending_count"));((Button)findViewById(R.id.doneTab)).setText("DONE\n"+r.optInt("done_count"));totalText.setText(r.optString("running_total","₹0"));});}catch(Exception e){runOnUiThread(()->statusText.setText("Connection error: "+e.getMessage()));}}).start();}
 private void loadOrders(boolean initial){progress.setVisibility(View.VISIBLE);statusText.setText((tab.equals("pending")?"Pending":"Done")+" orders load ho rahe hain…");new Thread(()->{try{JSONObject r=ApiClient.get(this,AppConfig.ORDERS_URL+"?type="+tab);if(r.optInt("_http_code")==401){runOnUiThread(this::forceLogin);return;}if(!r.optBoolean("ok"))throw new Exception(r.optString("message","Orders load nahi hue"));JSONArray arr=r.optJSONArray("orders");if(tab.equals("pending"))detectNew(arr,initial);runOnUiThread(()->render(arr));}catch(Exception e){runOnUiThread(()->{progress.setVisibility(View.GONE);statusText.setText("Connection error: "+e.getMessage());});}}).start();}
 private synchronized void detectNew(JSONArray arr,boolean initial){Set<String> now=new HashSet<>();int fresh=0;double amount=0;if(arr!=null)for(int i=0;i<arr.length();i++){JSONObject o=arr.optJSONObject(i);if(o==null)continue;String id=String.valueOf(o.optInt("id"));now.add(id);if(!firstLoad&&!knownPending.contains(id)){fresh++;amount+=o.optDouble("total_raw",0);}}knownPending.clear();knownPending.addAll(now);if(firstLoad||initial){firstLoad=false;return;}if(fresh>0)NotificationHelper.show(this,"🔔 "+fresh+" New Restaurant Order",fresh+" order aaye hain • Total ₹"+String.format("%.2f",amount));}
 private void render(JSONArray arr){progress.setVisibility(View.GONE);ordersContainer.removeAllViews();int n=arr==null?0:arr.length();statusText.setText((tab.equals("pending")?"Pending":"Done")+" Orders: "+n);if(n==0){TextView e=text("Abhi koi "+tab+" order nahi hai.",18,true);e.setGravity(Gravity.CENTER);e.setPadding(20,80,20,80);ordersContainer.addView(e);return;}for(int i=0;i<n;i++){JSONObject o=arr.optJSONObject(i);if(o!=null)ordersContainer.addView(card(o));}}
 private View card(JSONObject o){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(16),dp(14),dp(16),dp(14));c.setBackgroundResource(R.drawable.order_card);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(dp(12),dp(8),dp(12),dp(8));c.setLayoutParams(p);c.addView(text("📦 Order #"+o.optString("number"),21,true));c.addView(text("🕒 "+o.optString("date_created"),14,false));JSONArray items=o.optJSONArray("items");if(items!=null)for(int i=0;i<items.length();i++){JSONObject it=items.optJSONObject(i);if(it==null)continue;c.addView(text("• "+it.optInt("qty")+" × "+it.optString("name")+"\n   Rate: "+it.optString("rate")+"   |   Total: "+it.optString("line_total"),16,false));}String note=o.optString("customer_note","");if(!note.isEmpty())c.addView(text("📝 Note: "+note,15,false));TextView total=text("ORDER TOTAL: "+o.optString("total"),19,true);total.setTextColor(Color.rgb(255,122,0));c.addView(total);if(tab.equals("pending")){Button done=new Button(this);done.setText("✅ DONE / FOOD READY");done.setOnClickListener(v->confirmDone(o.optInt("id"),done));c.addView(done);}return c;}
 private void confirmDone(int id,Button b){new AlertDialog.Builder(this).setTitle("Order Done?").setMessage("Kya food ready ho gaya hai?").setNegativeButton("Nahi",null).setPositiveButton("Haan",(d,w)->done(id,b)).show();}
 private void done(int id,Button b){b.setEnabled(false);b.setText("Updating…");new Thread(()->{try{JSONObject body=new JSONObject();body.put("order_id",id);body.put("device_id",ApiClient.deviceId(this));JSONObject r=ApiClient.post(this,AppConfig.DONE_URL,body);if(!r.optBoolean("ok"))throw new Exception(r.optString("message","Update nahi hua"));runOnUiThread(()->{Toast.makeText(this,"Order Done ho gaya",Toast.LENGTH_SHORT).show();loadAll(false);});}catch(Exception e){runOnUiThread(()->{b.setEnabled(true);b.setText("✅ DONE / FOOD READY");Toast.makeText(this,e.getMessage(),Toast.LENGTH_LONG).show();});}}).start();}
 private void toggleOpen(CompoundButton v,boolean checked){if(ignoreSwitch)return;openSwitch.setEnabled(false);new Thread(()->{try{JSONObject b=new JSONObject();b.put("is_open",checked);b.put("device_id",ApiClient.deviceId(this));JSONObject r=ApiClient.post(this,AppConfig.SET_OPEN_URL,b);if(!r.optBoolean("ok"))throw new Exception(r.optString("message","Status change nahi hua"));runOnUiThread(()->{updateOpenLabel(r.optBoolean("is_open"));openSwitch.setEnabled(true);Toast.makeText(this,r.optString("message"),Toast.LENGTH_SHORT).show();});}catch(Exception e){runOnUiThread(()->{ignoreSwitch=true;openSwitch.setChecked(!checked);ignoreSwitch=false;openSwitch.setEnabled(true);Toast.makeText(this,e.getMessage(),Toast.LENGTH_LONG).show();});}}).start();}
 private void updateOpenLabel(boolean open){TextView t=findViewById(R.id.openStatusText);t.setText(open?"OPEN – Orders aa sakte hain":"CLOSED – Naye orders band");t.setTextColor(open?Color.rgb(18,148,71):Color.RED);}
 private void confirmReset(){new AlertDialog.Builder(this).setTitle("Total Reset").setMessage("Current total ₹0 ho jayega. Purana record admin me safe rahega.").setNegativeButton("Cancel",null).setPositiveButton("RESET",(d,w)->reset()).show();}
 private void reset(){new Thread(()->{try{JSONObject b=new JSONObject();b.put("device_id",ApiClient.deviceId(this));JSONObject r=ApiClient.post(this,AppConfig.RESET_URL,b);if(!r.optBoolean("ok"))throw new Exception(r.optString("message","Reset nahi hua"));runOnUiThread(()->{totalText.setText(r.optString("running_total","₹0"));Toast.makeText(this,"Total reset ho gaya",Toast.LENGTH_SHORT).show();});}catch(Exception e){runOnUiThread(()->Toast.makeText(this,e.getMessage(),Toast.LENGTH_LONG).show());}}).start();}
 private void styleTabs(){Button p=findViewById(R.id.pendingTab),d=findViewById(R.id.doneTab);p.setAlpha(tab.equals("pending")?1f:.55f);d.setAlpha(tab.equals("done")?1f:.55f);}
 private TextView text(String s,int size,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(Color.rgb(35,35,35));t.setPadding(0,dp(6),0,dp(6));if(bold)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}
 private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
}
